"""Create users and sales_funnel tables

Revision ID: e5b7ebd19046
Revises: 4aec32e8485e
Create Date: 2024-12-17 03:10:55.231803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5b7ebd19046'
down_revision = '4aec32e8485e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
